services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    container_name: django_app
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - envs/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - envs/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

volumes:
  mysql_data:
