services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    container_name: django_app
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/static
      - /app/media
    env_file:
      - envs/.env
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - envs/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s
  bot:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    image: support_bot
    command: python /app/Bot/main.py
    volumes:
      - .:/app
    env_file:
      - envs/.env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    logging:
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  static_volume:
  mysql_data:
  media_volume:
