# Generated by Django 5.0.3 on 2025-04-19 16:24

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqt"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="achievements/images/", verbose_name="Rasmi"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavhasi")),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sarlavhasi"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sarlavhasi"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sarlavhasi"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Matni")),
                (
                    "description_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Matni"),
                ),
                (
                    "description_en",
                    models.CharField(max_length=255, null=True, verbose_name="Matni"),
                ),
                (
                    "description_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Matni"),
                ),
            ],
            options={
                "verbose_name": "Muvaffaqiyat",
                "verbose_name_plural": "Muvaffaqiyatlar",
                "db_table": "achievements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Commentary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255, verbose_name="Avtor")),
                ("body", models.TextField(verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Izoh yozilgan vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Izoh",
                "verbose_name_plural": "Izohlar",
                "db_table": "comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=255, verbose_name="Ism-familiya"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(7)],
                        verbose_name="Telefon raqam",
                    ),
                ),
                ("message", models.TextField(verbose_name="Ma'lumot")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojat ",
                "verbose_name_plural": "Murojatlar",
                "db_table": "entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="partners/photos/", verbose_name="Hamkor logosi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hamkor",
                "verbose_name_plural": "Hamkorlar",
                "db_table": "partners",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqt"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
            ],
            options={
                "verbose_name": "Dori turi",
                "verbose_name_plural": "Dori turlari",
                "db_table": "types",
            },
        ),
        migrations.CreateModel(
            name="Pill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqt"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Nomi"),
                ),
                (
                    "body",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Dori haqida ma'lumot"
                    ),
                ),
                (
                    "body_uz",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Dori haqida ma'lumot"
                    ),
                ),
                (
                    "body_en",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Dori haqida ma'lumot"
                    ),
                ),
                (
                    "body_ru",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Dori haqida ma'lumot"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narxi"
                    ),
                ),
                (
                    "information",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tarkibi"
                    ),
                ),
                (
                    "information_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tarkibi"
                    ),
                ),
                (
                    "information_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tarkibi"
                    ),
                ),
                (
                    "information_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tarkibi"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(verbose_name="Yaroqlilik muddati"),
                ),
                (
                    "usage_url",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Foydalanish video manzili",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="pills/photos/", verbose_name="Rasmi"),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Chegirma narxi",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="Saytda ko'rinsinmi?"
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(default=False, verbose_name="Ommabopmi?"),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="apteka.category", verbose_name="Kategoriyalar"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pills",
                        to="apteka.type",
                        verbose_name="Dori turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dori",
                "verbose_name_plural": "Dorilar",
                "db_table": "pills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=255, verbose_name="Ism-familiya"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("message", models.TextField(verbose_name="Ma'lumot")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "pill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apteka.pill",
                        verbose_name="Dori id raqami",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma ",
                "verbose_name_plural": "Buyurtmalar",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqt"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=255, verbose_name="Ism-familiya"),
                ),
                (
                    "direction",
                    models.CharField(max_length=255, verbose_name="Yo'nalishi"),
                ),
                (
                    "direction_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Yo'nalishi"
                    ),
                ),
                (
                    "direction_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Yo'nalishi"
                    ),
                ),
                (
                    "direction_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Yo'nalishi"
                    ),
                ),
                (
                    "call",
                    models.CharField(max_length=20, verbose_name="Telefon raqami"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar"
                    ),
                ),
                (
                    "body_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar"
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar"
                    ),
                ),
                (
                    "body_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="doctors/photos/", verbose_name="Rasmi"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="Saytda ko'rinsinmi?"
                    ),
                ),
                (
                    "advices",
                    models.ManyToManyField(
                        related_name="doctors",
                        to="apteka.pill",
                        verbose_name="Tavsiya qilgan dorilari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doktor",
                "verbose_name_plural": "Doktorlar",
                "db_table": "doctors",
                "ordering": ["-created_at"],
            },
        ),
    ]
