# Generated by Django 5.0.3 on 2025-10-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_url", models.URLField(verbose_name="Telegram link")),
                ("instagram_url", models.URLField(verbose_name="Instagram link")),
                ("mail_url", models.URLField(verbose_name="Email link")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commentary",
            name="pill_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="apteka.pill",
                verbose_name="Dori id raqami",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pill",
            name="pill_count",
            field=models.IntegerField(default=1, verbose_name="Miqdori"),
            preserve_default=False,
        ),
    ]
